const LandObj = {
  en_US: {
    // Original portal translations
    please_enter_account: "Please enter a username. ",
    please_enter_pwd: "Please enter a password.",
    please_enter_access_code: "Please enter an access code.",
    login: "Login",
    accesscode: "Access Code",
    password: "Password",
    account: "Account",
    or: "or",
    one_click_login: "One-click Login",
    account_login: "Account Login",
    voucher_login: "Voucher Login",
    packages_title: "Internet Packages",
    contact_sales: "Contact",
    day: "Day",
    unlimited: "Unlimited",
    up_to_speed: "(up to 20–80 Mbps)",
    
    // Coverage Map translations
    coverage_map_title: "WiFi Coverage Area Map",
    coverage_map_subtitle: "Find our WiFi hotspots near you",
    refresh_map: "  🔄️  ",
    fullscreen: "  ⛶  ",
    legend: "Legend",
    AIS5G_location: "AIS5G WiFi Locations",
    AIS_location: "AIS. Wi-Fi Locations",
    buy_vouchers: "Buy Vouchers!",
    available_soon: "Available Soon",
    total_hotspots: "Total Locations",
    coverage_areas: "Coverage Areas",
    avg_speed: "Avg. Speed",
    active_users: "Active Users",
    back_to_portal: "← Back to Packages",
    go_to_packages: "See All Packages ➡️",
    wifi_coverage_map: "WiFi Coverage Map ➡️",
    need_help: "Need Help?"
  },
  th_TH: {
    // Original portal translations
    please_enter_account: "กรุณาป้อนชื่อผู้ใช้  ",
    please_enter_pwd: "กรุณาป้อนรหัสผ่าน ",
    please_enter_access_code: "กรุณาป้อนรหัสเข้าใช้งาน ",
    login: "เข้าสู่ระบบ ",
    accesscode: "รหัสเข้าใช้งาน ",
    password: "รหัสผ่าน ",
    account: "บัญชี ",
    or: "หรือ ",
    one_click_login: "เข้าสู่ระบบด้วยการคลิกเพียงครั้งเดียว ",
    account_login: "เข้าสู่ระบบบัญชี ",
    voucher_login: "เข้าสู่ระบบด้วยบัตรกำนัล ",
    packages_title: "แพ็กเกจอินเทอร์เน็ต",
    contact_sales: "ติดต่อ",
    day: "วัน",
    unlimited: "ไม่จำกัด",
    up_to_speed: "(สูงสุด 20–80 Mbps)",
    
    // Coverage Map translations
    coverage_map_title: "แผนที่พื้นที่ให้บริการ WiFi",
    coverage_map_subtitle: "ค้นหาจุด WiFi ใกล้คุณ",
    refresh_map: "  🔄️  ",
    fullscreen: "  ⛶  ",
    legend: "สัญลักษณ์",
    AIS5G_location: "จุดเชื่อมต่อ Wi-Fi",
    AIS_location: "สัญญาณปานกลาง",
    buy_vouchers: "สัญญาณอ่อน",
    available_soon: "ตำแหน่ง Hotspot",
    total_hotspots: "Hotspot ทั้งหมด",
    coverage_areas: "พื้นที่ให้บริการ",
    avg_speed: "ความเร็วเฉลี่ย",
    active_users: "ผู้ใช้งานออนไลน์",
    back_to_portal: "← กลับไปหน้าหลัก",
    go_to_packages: "ดูแพ็กเกจทั้งหมด ➡️",
    wifi_coverage_map: "แผนที่ครอบคลุมสัญญาณ WiFi ➡️",
    need_help: "ต้องการความช่วยเหลือ?"
  },
  my_MM: {
    // Original portal translations
    please_enter_account: "အမည် ထည့်ပါ။ ",
    please_enter_pwd: "လျှို့ဝှက်နံပါတ် ထည့်ပါ။ ",
    please_enter_access_code: "အသုံးပြုခွင့် ကုဒ် ထည့်ပါ။ ",
    login: "Login",
    accesscode: "အသုံးပြုခွင့် ကုဒ် ",
    password: "လျှို့ဝှက်နံပါတ် ",
    account: "အမည် ",
    or: "သို့မဟုတ် ",
    one_click_login: "ယာယီ Free သုံးရန် ",
    account_login: "အကောင့်ဖြင့် Login ဝင်ရန် ",
    voucher_login: "ဘောင်ချာဖြင့် Login ဝင်ရန် ",
    packages_title: "ပက်ကေ့ဂျ်များ",
    contact_sales: "ဆက်သွယ်ရန်",
    day: "ရက်",
    unlimited: "အကန့်အသတ်မရှိ",
    up_to_speed: "(20မှ80 Mbps အထိ)",
    
    // Coverage Map translations
    coverage_map_title: "WiFi လွှမ်းခြုံမှု မြေပုံ",
    coverage_map_subtitle: "သင့်အနီးရှိ WiFi နေရာများကို ရှာရန်",
    refresh_map: "  🔄️  ",
    fullscreen: "  ⛶  ",
    legend: "မြေပုံအညွှန်း",
    AIS5G_location: "AIS5G Wi-Fi အလွှင့်ဗူးများ",
    AIS_location: "AIS. Wi-Fi အလွှင့်ဗူးများ",
    buy_vouchers: "ဘောင်ချာဝယ်ယူနိုင်သည့် နေရာများ!",
    available_soon: "ထပ်မံတိုးချဲ့မည့် နေရာများ",
    total_hotspots: "စုစုပေါင်း Hotspot",
    coverage_areas: "လွှမ်းခြုံမှုဧရိယာ",
    avg_speed: "ပျမ်းမျှအမြန်နှုန်း",
    active_users: "အသုံးပြုသူပေါင်း",
    back_to_portal: "← Portal သို့ပြန်သွားရန်",
    go_to_packages: "ပက်ကေ့ဂျ်အားလုံး ကြည့်ရန် ➡️",
    wifi_coverage_map: "WiFi လွှမ်းခြုံမှု မြေပုံ ➡️",
    need_help: "အကူအညီလိုအပ်ပါသလား?"
  },
  zh_CN: {
    // Original portal translations
    please_enter_account: "请输入用户名。",
    please_enter_pwd: "请输入密码。",
    please_enter_access_code: "请输入访问码。",
    login: "登录 ",
    accesscode: "访问码 ",
    password: "密码 ",
    account: "账户 ",
    or: "或 ",
    one_click_login: "一键登录 ",
    account_login: "账户登录 ",
    voucher_login: "代金券登录 ",
    packages_title: "互联网套餐",
    contact_sales: "联系销售",
    day: "日",
    unlimited: "无限流量",
    up_to_speed: "(最高 20–80 Mbps)",
    
    coverage_map_title: "WiFi 覆盖范围地图",
    coverage_map_subtitle: "查找您附近的 WiFi 热点",
    refresh_map: "🔄️",
    fullscreen: "⛶",
    legend: "图例",
    AIS5G_location: "AIS5G WiFi 位置",
    AIS_location: "AIS WiFi 位置",
    buy_vouchers: "购买代金券！",
    available_soon: "即将推出",
    total_hotspots: "位置总数",
    coverage_areas: "覆盖区域",
    avg_speed: "平均速度",
    active_users: "活跃用户",
    back_to_portal: "← 返回套餐",
    go_to_packages: "查看所有套餐 ➡️",
    wifi_coverage_map: "WiFi 覆盖范围地图 ➡️",
    need_help: "需要帮助？"
  },
  vi_VN: {
    // Original portal translations
    please_enter_account: "Vui lòng nhập tên người dùng.",
    please_enter_pwd: "Vui lòng nhập mật khẩu.",
    please_enter_access_code: "Vui lòng nhập mã truy cập.",
    login: "Đăng nhập ",
    accesscode: "Mã truy cập ",
    password: "Mật khẩu ",
    account: "Tài khoản ",
    or: "hoặc",
    one_click_login: "Đăng nhập nhanh ",
    account_login: "Đăng nhập tài khoản ",
    voucher_login: "Đăng nhập phiếu giảm giá ",
    packages_title: "Gói cước Internet",
    contact_sales: "Liên hệ bộ phận bán hàng",
    day: "Ngày",
    unlimited: "Không giới hạn",
    up_to_speed: "(lên đến 20–80 Mbps)",
    
    // Coverage Map translations
    coverage_map_title: "Bản đồ vùng phủ sóng WiFi",
    coverage_map_subtitle: "Tìm điểm phát WiFi gần bạn",
    refresh_map: "  🔄️  ",
    fullscreen: "  ⛶  ",
    legend: "Chú giải",
    AIS5G_location: "Vị trí WiFi AIS5G",
    AIS_location: "Vị trí WiFi AIS",
    buy_vouchers: "Mua phiếu giảm giá!",
    available_soon: "Sắp có",
    total_hotspots: "Tổng số Hotspot",
    coverage_areas: "Khu vực phủ sóng",
    avg_speed: "Tốc độ TB",
    active_users: "Người dùng hoạt động",
    back_to_portal: "← Quay lại Portal",
    go_to_packages: "See All Packages ➡️",
    wifi_coverage_map: "WiFi Coverage Map ➡️",
    need_help: "Cần trợ giúp?"
  },
  es_ES: {
    // Original portal translations
    please_enter_account: "Introduzca el nombre de usuario.",
    please_enter_pwd: "Introduzca la contraseña.",
    please_enter_access_code: "por favor ingrese el código de verificación.",
    login: "Iniciar sesión",
    accesscode: "Código de acceso",
    password: "Contraseña",
    account: "Cuenta",
    or: "o",
    one_click_login: "Un solo clic",
    account_login: "Cuenta",
    voucher_login: "Gutschein-Anmeldung",
    packages_title: "Paquetes de Internet",
    contact_sales: "Contactar con Ventas",
    day: "Día",
    unlimited: "Ilimitado",
    up_to_speed: "(hasta 20–80 Mbps)",
    
    // Traducciones del mapa de cobertura
    coverage_map_title: "Mapa de la zona de cobertura WiFi",
    coverage_map_subtitle: "Encuentra nuestros puntos de acceso WiFi cerca de ti",
    refresh_map: " 🔄️ ",
    fullscreen: " ⛶ ",
    legend: "Leyenda",
    AIS5G_location: "Ubicaciones WiFi AIS5G",
    AIS_location: "Ubicaciones WiFi AIS",
    buy_vouchers: "¡Compra cupones!",
    available_soon: "Disponible pronto",
    total_hotspots: "Total de ubicaciones",
    coverage_areas: "Zonas de cobertura",
    avg_speed: "Velocidad media",
    active_users: "Usuarios activos",
    back_to_portal: "← Volver a Paquetes",
    go_to_packages: "Ver todos los paquetes ➡️",
    wifi_coverage_map: "Mapa de cobertura WiFi ➡️",
    need_help: "¿Necesitas ayuda?"
  },
};
